name: Update GitHub Profile README

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update README with Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: omkdev
          template: classic
          filename: metrics.svg
          base: activity, community, repositories, metadata
          repositories_affiliations: owner
          plugin_languages: yes
          plugin_languages_ignored: html, css
