name: GitHub Profile Metrics

on:
  schedule:
    - cron: "0 */12 * * *"   # updates every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          # ---------- BASIC SETUP ----------
          user: omkdev
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          filename: metrics.svg

          # ---------- PLUGINS ENABLED ----------
          plugin_calendar: yes
          plugin_calendar_limit: 1

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_followup: yes
          plugin_followup_sections: repositories

          plugin_topics: yes
          plugin_topics_limit: 30
          plugin_topics_mode: icons

          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 10

          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_notable_from: organization

          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_visibility: public
