name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Output file
          filename: metrics.svg

          # User
          user: omkdev
          template: classic
          base: header, activity, community, repositories, metadata

          # Plugins -----------------------------

          plugin_achievements: yes
          plugin_languages: yes
          plugin_calendar: yes
          plugin_habits: yes
          plugin_people: yes
          plugin_topics: yes
          plugin_pagespeed: yes

          # Pagespeed URL (must NOT be nested)
          plugin_pagespeed_url: https://omkdev.github.io/SplineRobo/
