name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg
          user: omkdev
          template: classic
          base: header, activity, community, repositories, metadata

          # -----------------------------
          # ðŸ”¥ PREMIUM FEATURES ENABLED
          # -----------------------------

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: X

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_sections: most-used

          plugin_calendar: yes
          plugin_calendar_ignored: no
          plugin_calendar_settings:
            chart_type: 3d

          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 24

          plugin_pagespeed: yes
          plugin_pagespeed_url: "https://omkdev.github.io/SplineRobo/"
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}

          plugin_topics: yes
          plugin_topics_limit: 30
          plugin_topics_mode: icons
